# 工作流名称
name: haha

# 触发条件
on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  push:
    branches:
      - master

# 作业
jobs:

  scheduled:
    strategy:
      matrix:
        random-hour: [9, 10, 11, 12, 13, 14, 15, 16, 17]
        random-minute: [0, 15, 30, 45]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scheduled at ${{ matrix.random-minute }} ${{ matrix.random-hour }}"

  autogreen:
    runs-on: ubuntu-latest
    steps:

      # 检出代码
      - name: Clone repository  
        uses: actions/checkout@v2

      # 获取当前分支的提交次数
      - name: Get commit count
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "Current commit count: $COMMIT_COUNT"

      # 获取指定城市的天气信息
      - name: Get weather
        run: |
          CITY="xian"
          WEATHER=$(curl -s "http://wttr.in/$CITY?format=%C+%t")
          echo "Current weather in $CITY: $WEATHER"
          
      # 自动提交
      - name: Auto green
        run: |
          # 配置 Git 用户信息
          git config --local user.email "lulumoee4@gmail.com"
          git config --local user.name "maxwei2002"
          
          # 设置远程仓库地址并授权
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
          # 拉取最新代码
          git fetch origin
          
          # 如果有新的提交，执行 rebase
          if ! git rev-parse --verify HEAD >/dev/null 2>&1
          then
            exit 0 # 第一次运行时忽略
          else
            git rebase origin/master
          fi
          
          # 创建一个空提交
          git commit --allow-empty -m "如果有一个女孩喜欢我,我一定会再爱它 $COMMIT_COUNT 次, 今日天气 $WEATHER"
          
          # 推送到远程仓库
          git push