# 工作流名称
name: haha

# 触发条件
on:
  schedule:
    - cron: ${{ env.RANDOM_SCHEDULE }}  # 使用随机生成的 cron 表达式
  push:
    branches:
      - master

# 作业
jobs:

  # 自动提交作业
  autogreen:
    # 使用最新版 Ubuntu 运行环境
    runs-on: ubuntu-latest
     
    # 作业步骤
    steps:

    # 生成随机的 cron 表达式
    - name: Generate random schedule
      run: |
        random_hour=$((9 + RANDOM % 9)) # 随机生成 9-17 之间的小时
        random_minute=$((RANDOM % 60)) # 随机生成 0-59 之间的分钟
        echo "RANDOM_SCHEDULE=0 $random_minute $random_hour * * 1-5" >> $GITHUB_ENV
      shell: bash

    # 检出代码
    - name: Clone repository
      uses: actions/checkout@v2

    # 获取当前分支的提交次数
    - name: Get commit count
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Current commit count: $COMMIT_COUNT"

    # 获取指定城市的天气信息
    - name: Get weather
      run: |
        CITY="xian" # 设置城市为西安
        WEATHER=$(curl -s "http://wttr.in/$CITY?format=%C+%t")
        echo "Current weather in $CITY: $WEATHER"

    # 自动提交
    - name: Auto green
      run: |
        # 配置 Git 用户信息
        git config --local user.email "lulumoee4@gmail.com"
        git config --local user.name "maxwei2002"
        
        # 设置远程仓库地址并授权
        git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        
        # 拉取最新代码
        git pull --rebase
        
        # 创建一个空提交,提交信息包含提交次数和天气信息
        git commit --allow-empty -m "如果有一个女孩喜欢我,我一定会再爱它 $COMMIT_COUNT 次, 今日天气 $WEATHER"
        
        # 推送到远程仓库
        git push